version: '3'
name: menu-app
services:
  node:
    container_name: backend-menu
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/code
    networks:
      - database
    links:
      - mongo-menu
  mongo-menu:
    image: mongo
    volumes:
      - mongodb:/data/db
    networks:
      - database

volumes:
  mongodb:

networks:
  database:
