version: '3'
name: menu-app
services:
  node:
    container_name: backend
    build: .
    ports:
      - 8080:80
    volumes:
      - ./:/code
    networks:
      - database
    links:
      - mongo
  menu-mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
    networks:
      - database

volumes:
  mongodb:

networks:
  database:
